language: python
python: 3.6

before_install:
  - URL='https://github.com/jgm/pandoc/releases/download/1.19.2.1/pandoc-1.19.2.1-1-amd64.deb'; FILE=`mktemp`; wget "$URL" -qO $FILE && sudo dpkg -i $FILE; rm $FILE
  - rvm install 2.3.3
  - nvm install node

install:
  - git config --file=.gitmodules submodule.static/articles.url https://$BITBUCKET_USER:$BITBUCKET_PASSWORD@bitbucket.org/davnn/articles
  - git submodule update --init --recursive
  - gem install bundler
  - pip install jupyter
  - npm install

script:
- bundle install
- npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: public
  on:
    branch: master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation

# disable the default submodule logic
git:
  submodules: false

sudo: false # route your build to the container-based infrastructure for a faster build
dist: trusty
