language: node_js
node_js:
  - "8"

install:
  - git config --file=.gitmodules submodule.static/articles.url https://davnn:$BITBUCKET_PASSWORD@bitbucket.org/davnn/articles
  - git submodule update --init --recursive --remote
  - npm install

script:
- npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: public
  on:
    branch: master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation

# Enable docker in builds
# See: https://docs.travis-ci.com/user/docker/
sudo: required
dist: trusty
services:
  - docker

# Disable the default git submodule logic
git:
  submodules: false
